# -*- coding: utf-8 -*-
"""data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IE2Q9xCVvcbDikUVi6tw6OpcqgiKmwou
"""

import pandas as pd
import numpy as np

#read the csv
df = pd.read_csv('data.csv')
df.head()

# Remove unnamed extra columns
df_clean = df.loc[:, ~df.columns.str.startswith('Unnamed')]
df_clean.head()

row_count_before = df_clean.shape[0]
missing_before = df_clean.isnull().sum()
row_count_before, missing_before

# 1. Trim spaces and standardize casing
df_clean['Name'] = df_clean['Name'].astype(str).str.strip().str.title()
df_clean['Region'] = df_clean['Region'].astype(str).str.upper()
df_clean.head()

# Replace missing Name values
df_clean['Name'] = df_clean['Name'].replace('Nan', 'Unnamed')
df_clean['Name'] = df_clean['Name'].fillna('Unnamed')
df_clean

# Clean and fill Marks
average_marks = df_clean['Marks'].mean()
df_clean['Marks'] = df_clean['Marks'].fillna(average_marks)
df_clean , average_marks

# Replace missing Region
df_clean['Region'] = df_clean['Region'].replace('NAN', 'UNKNOWN')
df_clean['Region'] = df_clean['Region'].fillna('UNKNOWN')
df_clean

# Convert Date
df_clean['Date'] = pd.to_datetime(df_clean['Date'], errors='coerce', dayfirst=True)
df_clean

df_clean = df_clean.drop_duplicates()
df_clean

# Result column
df_clean['Result'] = df_clean['Marks'].apply(lambda x: 'Pass' if x >= 70 else 'Fail')
df_clean

missing_after = df_clean.isnull().sum()
result_counts = df_clean.groupby(['Subject', 'Result']).size().unstack(fill_value=0)
missing_after

result_counts

# Save as CSV
df_clean.to_csv("dataset_cleaned.csv", index=False)

# Save as Excel
df_clean.to_excel("dataset_cleaned.xlsx", index=False)